### ISSUE TITLE
Breaks vim-prosession

### ISSUE THREAD

**Issue by rsheasby** [akiyosi/goneovim#122]
Hi,

Thanks for all the hard work on this. It's definitely my favourite neovim GUI I've used. There's one issue though. I usually rely on vim-prosession to automatically load my previous files and working directory. I've confirmed that this works correctly with nvim in the terminal. However, with goneovim it always launches at `/`, not loading my previous session. I'm running on macOS Catalina. I suspect the built-in workspace manager is interfering. I've tried disabling all goneovim features using 
```[editor]
ginitvim = '''
  augroup GonvimAu
    autocmd!
  augroup end
  augroup GonvimAuStatusline
    autocmd!
  augroup end
  augroup GonvimAuLint
    autocmd!
  augroup end
  augroup GonvimAuMd
    autocmd!
  augroup end
  augroup GonvimAuFilePath
    autocmd!
  augroup end
  augroup GonvimAuMinimap
    autocmd!
  augroup end
  augroup GonvimAuScrollbar
    autocmd!
  augroup end
'''
```

, but it still did not work.

**Comment by akiyosi** [comment]
Hi :)
Thanks for using goneovim.
Sorry for the late reply.

I began to investigate this issue.
Certainly launching from goneovim.app will give me an error.
However, booting from the terminal appears to restore the previous session.

```
/Applications/goneovim.app/Contents/MacOS/goneovim
```

Would that be the case in your environment as well?

I also believe that disabling Ginitvim in setting.toml is ineffective for this problem.

**Comment by akiyosi** [comment]
Hi,
This issue has been fixed in 2307784a46.
The problem was caused by the application's CWD being in the root directory when that launched and not having enough permissions for the plugin to work.
You can get the latest packages from Github-actions and try them out.
https://github.com/akiyosi/goneovim/actions/runs/126931606

**Comment by rsheasby** [comment]
Great, thanks! I'm actually not using vim much these days but if I get a chance to test it out and still get issues, I'll reopen the issue 😄
