### ISSUE TITLE
discoloring

### ISSUE THREAD

**Issue by eyalk5** [akiyosi/goneovim#132]
Hi, when I open leaderF , and also on other situations, I got wrong colors(bare text, with no colors highlighted).
It only happens at times after doing <down> for some time usually.

Here is how it should behave:
<img width="1316" alt="shouldbe" src="https://user-images.githubusercontent.com/23480511/83688982-f2119d80-a5f6-11ea-9d6f-931fa44332b8.png">
Here is how it behaves: 
<img width="1310" alt="discolor" src="https://user-images.githubusercontent.com/23480511/83688987-f3db6100-a5f6-11ea-92b7-7bd76c873ed6.png">

I know this doesn't happen in geovim-qt (at least not that often).

Both are screenshot from goneovim not launched from terminal. But it happens (probably more) from terminal. 
It seems that not all the lines that need to be redrawn are indeed redrawn.

**Comment by eyalk5** [comment]
It happens much more on vim visual multi , when selecting some words with <c-N>
here I compare it with nvim-qt .


![image](https://user-images.githubusercontent.com/23480511/83689680-1e79e980-a5f8-11ea-8432-ba56ce3741b6.png)

**Comment by akiyosi** [comment]
Hi :)
Thanks for the report on the issue.
I am going to investigate this issue.

If possible, could you get the latest package from github-actions and try to see if you get the same problem.
https://github.com/akiyosi/goneovim/actions/runs/124947498

**Comment by eyalk5** [comment]
It seems that I don't get the same problem. I do get another problem, though . Leaderf typing region appears in the bottom of the screen.
![image](https://user-images.githubusercontent.com/23480511/83919680-cbcd3880-a783-11ea-9d33-5014f442c3ec.png)

**Comment by eyalk5** [comment]
Another thing: 
au VimEnter * nested call OnLoad()

OnLoad wasn't called for some reason

**Comment by akiyosi** [comment]
Hi.
Thanks for the confirmation on the latest package.

I have found the cause of the Leaderf input window position issue.
I've discovered that in the current Neovim UI API, there is a bug in the message window position and We have implemented a workaround to compensate for this in the GUI front end. The Probably as a side effect of this, the input window position of Leaderf is also moved . Hmmm, I'll look into this solution.

I will also check the VimEnter issue as well.

**Comment by akiyosi** [comment]
I have tried to fix the problem.
It works in my environment, but how does it work in yours?

https://github.com/akiyosi/goneovim/actions/runs/127653606


> Another thing:
> au VimEnter * nested call OnLoad()
> OnLoad wasn't called for some reason

I have looked into this, but cannot reproduce the problem.
What function specifically do you have set up as `OnLoad()`? Also, is it possible that other plugins are affecting it?

**Comment by eyalk5** [comment]
Leaderf still doesn't work correctly. Have you tried the same settings?
OnLoad was called. Probably my mistake, although strange. 
Thanks for all the effort.

**Comment by eyalk5** [comment]
Indeed, it works well in the last version you have sent. I checked previous versions and didn't work. Thanks!
