### ISSUE TITLE
not able to use goneovim

### ISSUE THREAD

**Issue by lalitmee** [akiyosi/goneovim#196]
I am facing some weird issue in running `goneovim` on `Pop-os 20.04`. I am trying to run `goneovim` after installing the Linux asset from the repo and then run the executable from the command line. I am getting this error in my terminal and it crashes right away.

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xde7f6c]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*Screen).toolTipPos(0xc0000bedc0, 0x10, 0xc0003e2668, 0x0, 0x7ffd158e2aa0)
        github.com/akiyosi/goneovim/editor/screen.go:520 +0x4c
github.com/akiyosi/goneovim/editor.(*Workspace).InputMethodQuery(0xc000391880, 0x2, 0x41fb1f0)
        github.com/akiyosi/goneovim/editor/workspace.go:2375 +0x42
github.com/therecipe/qt/widgets.callbackQWidget_InputMethodQuery(0x41fb1f0, 0x2, 0x45cc840)
        github.com/therecipe/qt/widgets/widgets-minimal.go:25145 +0x6b
github.com/therecipe/qt/widgets._cgoexpwrap_4ee128feccc4_callbackQWidget_InputMethodQuery(0x41fb1f0, 0x2, 0x0)
        _cgo_gotypes.go:27983 +0x72
github.com/therecipe/qt/widgets._Cfunc_QWidget_EventDefault(0x41fb1f0, 0x7ffd158e2170, 0x0)
        _cgo_gotypes.go:19808 +0x4a
github.com/therecipe/qt/widgets.(*QWidget).EventDefault.func1(0xc000550f50, 0x13542e0, 0xc0004e8598, 0xc0004e8598)
        github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0xb6
github.com/therecipe/qt/widgets.(*QWidget).EventDefault(0xc000550f50, 0x13542e0, 0xc0004e8598, 0x5)
        github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0x4d
github.com/therecipe/qt/widgets.callbackQWidget_Event(0x41fb1f0, 0x7ffd158e2170, 0x7ffd158e2780)
        github.com/therecipe/qt/widgets/widgets-minimal.go:24619 +0x120
github.com/therecipe/qt/widgets._cgoexpwrap_4ee128feccc4_callbackQWidget_Event(0x41fb1f0, 0x7ffd158e2170, 0x0)
        _cgo_gotypes.go:27850 +0x35
github.com/therecipe/qt/gui._Cfunc_QInputMethod_Update(0x40c8be0, 0x2)
        _cgo_gotypes.go:6058 +0x45
github.com/therecipe/qt/gui.(*QInputMethod).Update.func1(0xc0004e8580, 0x2)
        github.com/therecipe/qt/gui/gui-minimal.go:6099 +0x6e
github.com/therecipe/qt/gui.(*QInputMethod).Update(0xc0004e8580, 0x2)
        github.com/therecipe/qt/gui/gui-minimal.go:6099 +0x4d
github.com/akiyosi/goneovim/editor.(*Cursor).move(0xc0001f58c0)
        github.com/akiyosi/goneovim/editor/cursor.go:248 +0x69
github.com/akiyosi/goneovim/editor.(*Cursor).update(0xc0001f58c0)
        github.com/akiyosi/goneovim/editor/cursor.go:413 +0x245
github.com/akiyosi/goneovim/editor.(*Workspace).handleRedraw(0xc000391880, 0xc0004d2000, 0x74, 0x74)
        github.com/akiyosi/goneovim/editor/workspace.go:1209 +0x170d
github.com/akiyosi/goneovim/editor.(*Workspace).registerSignal.func1()
        github.com/akiyosi/goneovim/editor/workspace.go:361 +0x7d
github.com/akiyosi/goneovim/editor.callbackworkspaceSignal28652a_RedrawSignal(0x4138cc0)
        github.com/akiyosi/goneovim/editor/moc.go:617 +0x68
github.com/akiyosi/goneovim/editor._cgoexpwrap_a7ecf0d2f817_callbackworkspaceSignal28652a_RedrawSignal(0x4138cc0)
        _cgo_gotypes.go:4631 +0x2b
github.com/akiyosi/goneovim/editor._Cfunc_workspaceSignal28652a_EventDefault(0x4138cc0, 0x7faae4002020, 0x0)
        _cgo_gotypes.go:4029 +0x4a
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault.func1(0xc0003a40a0, 0x13542e0, 0xc00049ac80, 0xc00049ac80)
        github.com/akiyosi/goneovim/editor/moc.go:1233 +0xb6
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault(0xc0003a40a0, 0x13542e0, 0xc00049ac80, 0x5)
        github.com/akiyosi/goneovim/editor/moc.go:1233 +0x4d
github.com/akiyosi/goneovim/editor.callbackworkspaceSignal28652a_Event(0x4138cc0, 0x7faae4002020, 0x11bcab0)
        github.com/akiyosi/goneovim/editor/moc.go:1228 +0x11e
github.com/akiyosi/goneovim/editor._cgoexpwrap_a7ecf0d2f817_callbackworkspaceSignal28652a_Event(0x4138cc0, 0x7faae4002020, 0x1)
        _cgo_gotypes.go:4826 +0x35
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
        _cgo_gotypes.go:2600 +0x49
github.com/therecipe/qt/widgets.QApplication_Exec(...)
        github.com/therecipe/qt/widgets/widgets-minimal.go:2983
github.com/akiyosi/goneovim/editor.InitEditor(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/akiyosi/goneovim/editor/editor.go:341 +0xe5e
main.main()
        github.com/akiyosi/goneovim/cmd/goneovim/main.go:30 +0xa3
```

Yesterday, there was a release so I thought it may be fixed but no it's the same thing still. So now I am guessing that it may be something with my configuration of the system.

Can someone please help me? :cry:  
I love `goneovim` and `Golang` :innocent: . I just wanna use this.

**Comment by akiyosi** [comment]
Hi :D
I have fixed what I think is the cause of this problem.
Could you please try the following.

https://github.com/akiyosi/goneovim/actions/runs/570333910

**Comment by lalitmee** [comment]
@akiyosi , I am not getting how to download the release assets from the Github Actions page. Can you please help me? I tried looking for assets there but didn't find anything.

**Comment by lalitmee** [comment]
Hey @akiyosi , I am still getting the same error after trying the latest action download.

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe0dcad]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*Screen).toolTipMove(0xc0002cc0a0, 0x0, 0x0)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/screen.go:563 +0x2d
github.com/akiyosi/goneovim/editor.(*Workspace).InputMethodQuery(0xc0002ca000, 0x2, 0x42540f0)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/workspace.go:2376 +0x72
github.com/therecipe/qt/widgets.callbackQWidget_InputMethodQuery(0x42540f0, 0x2, 0xc0004bcea0)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:25145 +0x6b
github.com/therecipe/qt/widgets._cgoexpwrap_640c2d588004_callbackQWidget_InputMethodQuery(0x42540f0, 0x2, 0x0)
        _cgo_gotypes.go:27983 +0x64
github.com/therecipe/qt/widgets._Cfunc_QWidget_EventDefault(0x42540f0, 0x7fffc0a25fa0, 0x0)
        _cgo_gotypes.go:19808 +0x4a
github.com/therecipe/qt/widgets.(*QWidget).EventDefault.func1(0xc0004bd0d8, 0x14204a0, 0xc0003d8308, 0xc0003d8308)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0xb9
github.com/therecipe/qt/widgets.(*QWidget).EventDefault(0xc0004bd0d8, 0x14204a0, 0xc0003d8308, 0x5)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0x4f
github.com/therecipe/qt/widgets.callbackQWidget_Event(0x42540f0, 0x7fffc0a25fa0, 0x7f0c38c8a9e8)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24619 +0x126
github.com/therecipe/qt/widgets._cgoexpwrap_640c2d588004_callbackQWidget_Event(0x42540f0, 0x7fffc0a25fa0, 0x0)
        _cgo_gotypes.go:27850 +0x35
github.com/therecipe/qt/gui._Cfunc_QInputMethod_Update(0x3a87c30, 0x2)
        _cgo_gotypes.go:6058 +0x45
github.com/therecipe/qt/gui.(*QInputMethod).Update.func1(0xc0003d82f8, 0x2)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/gui/gui-minimal.go:6099 +0x70
github.com/therecipe/qt/gui.(*QInputMethod).Update(0xc0003d82f8, 0x2)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/gui/gui-minimal.go:6099 +0x4f
github.com/akiyosi/goneovim/editor.(*Cursor).move(0xc0002de000)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/cursor.go:248 +0x69
github.com/akiyosi/goneovim/editor.(*Cursor).update(0xc0002de000)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/cursor.go:413 +0x246
github.com/akiyosi/goneovim/editor.(*Workspace).handleRedraw(0xc0002ca000, 0xc0003fc000, 0x74, 0x74)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/workspace.go:1209 +0x1750
github.com/akiyosi/goneovim/editor.(*Workspace).registerSignal.func1()
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/workspace.go:361 +0x7d
github.com/akiyosi/goneovim/editor.callbackworkspaceSignalada841_RedrawSignal(0x3d353e0)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/moc.go:1171 +0x68
github.com/akiyosi/goneovim/editor._cgoexpwrap_1a07396d7d1e_callbackworkspaceSignalada841_RedrawSignal(0x3d353e0)
        _cgo_gotypes.go:4898 +0x2b
github.com/akiyosi/goneovim/editor._Cfunc_workspaceSignalada841_EventDefault(0x3d353e0, 0x7f0c2c000fa0, 0x0)
        _cgo_gotypes.go:4097 +0x4a
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault.func1(0xc0002b6000, 0x14204a0, 0xc0003faf38, 0xc0003faf38)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/moc.go:1825 +0xb9
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault(0xc0002b6000, 0x14204a0, 0xc0003faf38, 0x5)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/moc.go:1825 +0x4f
github.com/akiyosi/goneovim/editor.callbackworkspaceSignalada841_Event(0x3d353e0, 0x7f0c2c000fa0, 0x11e2738)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/moc.go:1820 +0x121
github.com/akiyosi/goneovim/editor._cgoexpwrap_1a07396d7d1e_callbackworkspaceSignalada841_Event(0x3d353e0, 0x7f0c2c000fa0, 0x3ae7750)
        _cgo_gotypes.go:5093 +0x35
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
        _cgo_gotypes.go:2600 +0x49
github.com/therecipe/qt/widgets.QApplication_Exec(...)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:2983
github.com/akiyosi/goneovim/editor.InitEditor(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/editor.go:341 +0xf5b
main.main()
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/cmd/goneovim/main.go:30 +0xa3
```

**Comment by akiyosi** [comment]
Hmm, this is a strange issue. I haven't tested it on Pop OS, but it may be that there is something deeper going on that makes the order of object creation different from the major order.
I'll start working on a fix related to this issue now.

**Comment by akiyosi** [comment]
I also fixed some code that I think is related to the problem.
Could you please try it out?

https://github.com/akiyosi/goneovim/actions/runs/571577439

**Comment by lalitmee** [comment]
@akiyosi , there are three types of packages being formed in action result. How all those three are different?

Three are:
1. `5.13.0`
2. `5.14.1`
3. `5.15.1`

**Comment by lalitmee** [comment]
@akiyosi , I tried `5.15.1` and I am still getting the same error.

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe401ed]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*Workspace).InputMethodQuery(0xc0002bc000, 0x2, 0x2ae0b10)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/workspace.go:2380 +0xbd
github.com/therecipe/qt/widgets.callbackQWidget_InputMethodQuery(0x2ae0b10, 0x2, 0xc0004c4ea0)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:25145 +0x6b
github.com/therecipe/qt/widgets._cgoexpwrap_640c2d588004_callbackQWidget_InputMethodQuery(0x2ae0b10, 0x2, 0x0)
        _cgo_gotypes.go:27983 +0x64
github.com/therecipe/qt/widgets._Cfunc_QWidget_EventDefault(0x2ae0b10, 0x7ffd1ac3c6e0, 0x0)
        _cgo_gotypes.go:19808 +0x4a
github.com/therecipe/qt/widgets.(*QWidget).EventDefault.func1(0xc0004c50d8, 0x1420520, 0xc000290f58, 0xc000290f58)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0xb9
github.com/therecipe/qt/widgets.(*QWidget).EventDefault(0xc0004c50d8, 0x1420520, 0xc000290f58, 0x5)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0x4f
github.com/therecipe/qt/widgets.callbackQWidget_Event(0x2ae0b10, 0x7ffd1ac3c6e0, 0x7ffd1ac3cca0)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24619 +0x126
github.com/therecipe/qt/widgets._cgoexpwrap_640c2d588004_callbackQWidget_Event(0x2ae0b10, 0x7ffd1ac3c6e0, 0x0)
        _cgo_gotypes.go:27850 +0x35
github.com/therecipe/qt/gui._Cfunc_QInputMethod_Update(0x29a5840, 0x2)
        _cgo_gotypes.go:6058 +0x45
github.com/therecipe/qt/gui.(*QInputMethod).Update.func1(0xc000290f48, 0x2)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/gui/gui-minimal.go:6099 +0x70
github.com/therecipe/qt/gui.(*QInputMethod).Update(0xc000290f48, 0x2)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/gui/gui-minimal.go:6099 +0x4f
github.com/akiyosi/goneovim/editor.(*Cursor).move(0xc0002d2000)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/cursor.go:248 +0x69
github.com/akiyosi/goneovim/editor.(*Cursor).update(0xc0002d2000)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/cursor.go:413 +0x246
github.com/akiyosi/goneovim/editor.(*Workspace).handleRedraw(0xc0002bc000, 0xc00016d800, 0x74, 0x74)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/workspace.go:1209 +0x1750
github.com/akiyosi/goneovim/editor.(*Workspace).registerSignal.func1()
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/workspace.go:361 +0x7d
github.com/akiyosi/goneovim/editor.callbackworkspaceSignalada841_RedrawSignal(0x2cd6090)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/moc.go:1171 +0x68
github.com/akiyosi/goneovim/editor._cgoexpwrap_1a07396d7d1e_callbackworkspaceSignalada841_RedrawSignal(0x2cd6090)
        _cgo_gotypes.go:4898 +0x2b
github.com/akiyosi/goneovim/editor._Cfunc_workspaceSignalada841_EventDefault(0x2cd6090, 0x2a55a80, 0x0)
        _cgo_gotypes.go:4097 +0x4a
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault.func1(0xc00029c050, 0x1420520, 0xc000410ed0, 0xc000410ed0)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/moc.go:1825 +0xb9
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault(0xc00029c050, 0x1420520, 0xc000410ed0, 0x5)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/moc.go:1825 +0x4f
github.com/akiyosi/goneovim/editor.callbackworkspaceSignalada841_Event(0x2cd6090, 0x2a55a80, 0x11e27b8)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/moc.go:1820 +0x121
github.com/akiyosi/goneovim/editor._cgoexpwrap_1a07396d7d1e_callbackworkspaceSignalada841_Event(0x2cd6090, 0x2a55a80, 0x7fd318002960)
        _cgo_gotypes.go:5093 +0x35
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
        _cgo_gotypes.go:2600 +0x49
github.com/therecipe/qt/widgets.QApplication_Exec(...)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:2983
github.com/akiyosi/goneovim/editor.InitEditor(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/editor.go:341 +0xf5b
main.main()
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/cmd/goneovim/main.go:30 +0xa3

```

**Comment by akiyosi** [comment]
I'm sorry again and again.😅
Can you please try the following again?
https://github.com/akiyosi/goneovim/actions/runs/573200177

**Comment by lalitmee** [comment]
@akiyosi, no problem. I am also a developer. I know how this goes. :wink:

But one thing is for sure that until and unless it is fixed I will be commenting here because I love this `goneovim`. It's in golang. :heart:

**Comment by lalitmee** [comment]
@akiyosi , yeah now I can use it. I will try it and let you know if I face any problem again in this.

**Comment by lalitmee** [comment]
@akiyosi, I tried but still I am getting this.
This time it was working without passing any nvim path but when I passed nvim path of `0.5` version nvim. It crashed.

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xde5bf9]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*RGBA).brend(...)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/rgba.go:67
github.com/akiyosi/goneovim/editor.(*Cursor).paint(0xc000217440, 0xc0006b5a40)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/cursor.go:94 +0x109
github.com/therecipe/qt/widgets.callbackQWidget_PaintEvent(0x34d2d60, 0x7ffc26d8b970)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:25920 +0x9f
github.com/therecipe/qt/widgets._cgoexpwrap_640c2d588004_callbackQWidget_PaintEvent(0x34d2d60, 0x7ffc26d8b970)
        _cgo_gotypes.go:28171 +0x35
github.com/therecipe/qt/widgets._Cfunc_QWidget_EventDefault(0x34d2d60, 0x7ffc26d8b970, 0x0)
        _cgo_gotypes.go:19808 +0x4a
github.com/therecipe/qt/widgets.(*QWidget).EventDefault.func1(0xc0005774a8, 0x1420520, 0xc0006b5a38, 0xc0006b5a38)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0xb9
github.com/therecipe/qt/widgets.(*QWidget).EventDefault(0xc0005774a8, 0x1420520, 0xc0006b5a38, 0x5)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0x4f
github.com/therecipe/qt/widgets.callbackQWidget_Event(0x34d2d60, 0x7ffc26d8b970, 0x11e27b8)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24619 +0x126
github.com/therecipe/qt/widgets._cgoexpwrap_640c2d588004_callbackQWidget_Event(0x34d2d60, 0x7ffc26d8b970, 0x0)
        _cgo_gotypes.go:27850 +0x35
github.com/akiyosi/goqtframelesswindow._Cfunc_QFramelessWindowb0996f_EventDefault(0x36dd680, 0x36c86e0, 0x0)
        _cgo_gotypes.go:350 +0x4a
github.com/akiyosi/goqtframelesswindow.(*QFramelessWindow).EventDefault.func1(0xc0002ce000, 0x1420520, 0xc0006b56e0, 0xc0006b56e0)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goqtframelesswindow/moc.go:504 +0xbd
github.com/akiyosi/goqtframelesswindow.(*QFramelessWindow).EventDefault(0xc0002ce000, 0x1420520, 0xc0006b56e0, 0x5)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goqtframelesswindow/moc.go:504 +0x53
github.com/akiyosi/goqtframelesswindow.callbackQFramelessWindowb0996f_Event(0x36dd680, 0x36c86e0, 0x11e27b8)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goqtframelesswindow/moc.go:499 +0x121
github.com/akiyosi/goqtframelesswindow._cgoexpwrap_16595c21a290_callbackQFramelessWindowb0996f_Event(0x36dd680, 0x36c86e0, 0x1)
        _cgo_gotypes.go:1631 +0x35
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
        _cgo_gotypes.go:2600 +0x49
github.com/therecipe/qt/widgets.QApplication_Exec(...)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:2983
github.com/akiyosi/goneovim/editor.InitEditor(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffc26d8ed51, 0xd, 0x0, ...)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/editor.go:341 +0xf5b
main.main()
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/cmd/goneovim/main.go:30 +0xa3

```

**Comment by akiyosi** [comment]
Hi,
I created a virtual machine for Pop!OS and was able to reproduce this set of problems.
In my environment, the following fixes seem to have fixed the problem. 
Could you please try it in your environment as well?

https://github.com/akiyosi/goneovim/actions/runs/580335435

**Comment by lalitmee** [comment]
Hey @akiyosi , I am still getting the error.

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xde61c7]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*RGBA).QColor(...)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/rgba.go:76
github.com/akiyosi/goneovim/editor.(*Cursor).newCharCache(0xc0002fa000, 0x22c3fe5, 0x1, 0x0, 0x1, 0x14202c0)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/cursor.go:175 +0x137
github.com/akiyosi/goneovim/editor.(*Cursor).paint(0xc0002fa000, 0xc00031abb0)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/cursor.go:118 +0x531
github.com/therecipe/qt/widgets.callbackQWidget_PaintEvent(0x3cb8fc0, 0x7ffcfd932f70)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:25920 +0x9f
github.com/therecipe/qt/widgets._cgoexpwrap_8be956a440dd_callbackQWidget_PaintEvent(0x3cb8fc0, 0x7ffcfd932f70)
        _cgo_gotypes.go:28171 +0x35
github.com/therecipe/qt/widgets._Cfunc_QWidget_EventDefault(0x3cb8fc0, 0x7ffcfd932f70, 0x0)
        _cgo_gotypes.go:19808 +0x4a
github.com/therecipe/qt/widgets.(*QWidget).EventDefault.func1(0xc0006cb4a8, 0x14204a0, 0xc00031aba8, 0xc00031aba8)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0xb9
github.com/therecipe/qt/widgets.(*QWidget).EventDefault(0xc0006cb4a8, 0x14204a0, 0xc00031aba8, 0x5)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0x4f
github.com/therecipe/qt/widgets.callbackQWidget_Event(0x3cb8fc0, 0x7ffcfd932f70, 0x11e2718)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24619 +0x126
github.com/therecipe/qt/widgets._cgoexpwrap_8be956a440dd_callbackQWidget_Event(0x3cb8fc0, 0x7ffcfd932f70, 0x0)
        _cgo_gotypes.go:27850 +0x35
github.com/akiyosi/goqtframelesswindow._Cfunc_QFramelessWindowb0996f_EventDefault(0x3d14450, 0x435e340, 0x0)
        _cgo_gotypes.go:350 +0x4a
github.com/akiyosi/goqtframelesswindow.(*QFramelessWindow).EventDefault.func1(0xc000235b00, 0x14204a0, 0xc00031a730, 0xc00031a730)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goqtframelesswindow/moc.go:504 +0xbd
github.com/akiyosi/goqtframelesswindow.(*QFramelessWindow).EventDefault(0xc000235b00, 0x14204a0, 0xc00031a730, 0x5)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goqtframelesswindow/moc.go:504 +0x53
github.com/akiyosi/goqtframelesswindow.callbackQFramelessWindowb0996f_Event(0x3d14450, 0x435e340, 0x11e2718)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goqtframelesswindow/moc.go:499 +0x121
github.com/akiyosi/goqtframelesswindow._cgoexpwrap_0056b4a1b1b7_callbackQFramelessWindowb0996f_Event(0x3d14450, 0x435e340, 0x1)
        _cgo_gotypes.go:1631 +0x35
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
        _cgo_gotypes.go:2600 +0x49
github.com/therecipe/qt/widgets.QApplication_Exec(...)
        /home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:2983
github.com/akiyosi/goneovim/editor.InitEditor(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/editor.go:341 +0xf5b
main.main()
        /home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/cmd/goneovim/main.go:30 +0xa3
```

How I am running it is that I extract the zip files in a folder called `goneovim` in my `HOME` directory. And then I have an alias in my `zshrc` which is `alias gnvim=~/goneovim/goneovim` and then I run that alias and for a flash of second, it shows a white screen, and then it crashes.

**Comment by akiyosi** [comment]
@lalitmee 
Hmmm... I still don't know exactly why only Pop!os has this specific problem.
I've made a new fix. I'm sorry, but I would appreciate it if you could check if it works.

https://github.com/akiyosi/goneovim/actions/runs/589367881

**Comment by lalitmee** [comment]
Hey @akiyosi , this time I am getting a different error. something related to goroutine.

```bash
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fe363bc3f49]

runtime stack:
runtime.throw(0x1181798, 0x2a)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xf03d00, 0xc000695020, 0xc000695040)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/cgocall.go:128 +0x5b fp=0xc000694ff0 sp=0xc000694fb8 pc=0x579b3b
github.com/therecipe/qt/gui._Cfunc_QPainter_SetPen2(0x38e28a0, 0x0)
	_cgo_gotypes.go:11137 +0x45 fp=0xc000695020 sp=0xc000694ff0 pc=0x729c85
github.com/therecipe/qt/gui.(*QPainter).SetPen2.func1(0xc000296950, 0x1420b60, 0x0)
	/home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/gui/gui-minimal.go:11198 +0xb3 fp=0xc000695068 sp=0xc000695020 pc=0x7adaa3
github.com/therecipe/qt/gui.(*QPainter).SetPen2(0xc000296950, 0x1420b60, 0x0)
	/home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/gui/gui-minimal.go:11198 +0x57 fp=0xc000695090 sp=0xc000695068 pc=0x76a6e7
github.com/akiyosi/goneovim/editor.(*Cursor).newCharCache(0xc0002a0240, 0x22c4fe5, 0x1, 0x0, 0x1, 0x14207a0)
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/cursor.go:175 +0x15c fp=0xc000695100 sp=0xc000695090 pc=0xde62bc
github.com/akiyosi/goneovim/editor.(*Cursor).paint(0xc0002a0240, 0xc000296900)
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/cursor.go:118 +0x582 fp=0xc0006951d0 sp=0xc000695100 pc=0xde6042
github.com/akiyosi/goneovim/editor.(*Cursor).paint-fm(0xc000296900)
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/cursor.go:64 +0x34 fp=0xc0006951f0 sp=0xc0006951d0 pc=0xe90cf4
github.com/therecipe/qt/widgets.callbackQWidget_PaintEvent(0x2e501d0, 0x7ffe08ddfe70)
	/home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:25920 +0x9f fp=0xc000695240 sp=0xc0006951f0 pc=0x89365f
github.com/therecipe/qt/widgets._cgoexpwrap_8be956a440dd_callbackQWidget_PaintEvent(0x2e501d0, 0x7ffe08ddfe70)
	_cgo_gotypes.go:28171 +0x35 fp=0xc000695260 sp=0xc000695240 pc=0x816bb5
runtime.call32(0x0, 0x7ffe08ddf9a0, 0x7ffe08ddfa30, 0x10)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/asm_amd64.s:519 +0x3b fp=0xc000695290 sp=0xc000695260 pc=0x5cc9cb
runtime.cgocallbackg1(0x0)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/cgocall.go:314 +0x177 fp=0xc000695308 sp=0xc000695290 pc=0x579ea7
runtime.cgocallbackg(0x0)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/cgocall.go:191 +0xc5 fp=0xc000695370 sp=0xc000695308 pc=0x579c95
runtime.cgocallback_gofunc(0x579b5f, 0xf43490, 0xc000695400, 0xc0006953f0)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/asm_amd64.s:773 +0x9b fp=0xc000695390 sp=0xc000695370 pc=0x5cdf9b
runtime.asmcgocall(0xf43490, 0xc000695400)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/asm_amd64.s:620 +0x42 fp=0xc000695398 sp=0xc000695390 pc=0x5cde32
runtime.cgocall(0xf43490, 0xc000695400, 0x8)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/cgocall.go:131 +0x7f fp=0xc0006953d0 sp=0xc000695398 pc=0x579b5f
github.com/therecipe/qt/widgets._Cfunc_QWidget_EventDefault(0x2e501d0, 0x7ffe08ddfe70, 0x0)
	_cgo_gotypes.go:19808 +0x4a fp=0xc000695400 sp=0xc0006953d0 pc=0x7fc96a
github.com/therecipe/qt/widgets.(*QWidget).EventDefault.func1(0xc0006954a8, 0x1420980, 0xc0002968f8, 0xc0002968f8)
	/home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0xb9 fp=0xc000695448 sp=0xc000695400 pc=0x8deb89
github.com/therecipe/qt/widgets.(*QWidget).EventDefault(0xc0006954a8, 0x1420980, 0xc0002968f8, 0x5)
	/home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24653 +0x4f fp=0xc000695478 sp=0xc000695448 pc=0x88b38f
github.com/therecipe/qt/widgets.callbackQWidget_Event(0x2e501d0, 0x7ffe08ddfe70, 0x11e2eb8)
	/home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:24619 +0x126 fp=0xc0006954c8 sp=0xc000695478 pc=0x88b016
github.com/therecipe/qt/widgets._cgoexpwrap_8be956a440dd_callbackQWidget_Event(0x2e501d0, 0x7ffe08ddfe70, 0x0)
	_cgo_gotypes.go:27850 +0x35 fp=0xc0006954f0 sp=0xc0006954c8 pc=0x815a65
runtime.call32(0x0, 0x7ffe08ddfbb0, 0x7ffe08ddfc40, 0x18)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/asm_amd64.s:519 +0x3b fp=0xc000695520 sp=0xc0006954f0 pc=0x5cc9cb
runtime.cgocallbackg1(0x0)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/cgocall.go:314 +0x177 fp=0xc000695598 sp=0xc000695520 pc=0x579ea7
runtime.cgocallbackg(0x0)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/cgocall.go:191 +0xc5 fp=0xc000695600 sp=0xc000695598 pc=0x579c95
runtime.cgocallback_gofunc(0x579b5f, 0xf7f410, 0xc000695690, 0xc000695680)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/asm_amd64.s:773 +0x9b fp=0xc000695620 sp=0xc000695600 pc=0x5cdf9b
runtime.asmcgocall(0xf7f410, 0xc000695690)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/asm_amd64.s:620 +0x42 fp=0xc000695628 sp=0xc000695620 pc=0x5cde32
runtime.cgocall(0xf7f410, 0xc000695690, 0x8)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/cgocall.go:131 +0x7f fp=0xc000695660 sp=0xc000695628 pc=0x579b5f
github.com/akiyosi/goqtframelesswindow._Cfunc_QFramelessWindowb0996f_EventDefault(0x2f86a10, 0x38698d0, 0x0)
	_cgo_gotypes.go:350 +0x4a fp=0xc000695690 sp=0xc000695660 pc=0x98164a
github.com/akiyosi/goqtframelesswindow.(*QFramelessWindow).EventDefault.func1(0xc0002a0000, 0x1420980, 0xc000296448, 0xc000296448)
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goqtframelesswindow/moc.go:504 +0xbd fp=0xc0006956d8 sp=0xc000695690 pc=0x9907dd
github.com/akiyosi/goqtframelesswindow.(*QFramelessWindow).EventDefault(0xc0002a0000, 0x1420980, 0xc000296448, 0x5)
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goqtframelesswindow/moc.go:504 +0x53 fp=0xc000695708 sp=0xc0006956d8 pc=0x9887b3
github.com/akiyosi/goqtframelesswindow.callbackQFramelessWindowb0996f_Event(0x2f86a10, 0x38698d0, 0x11e2eb8)
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goqtframelesswindow/moc.go:499 +0x121 fp=0xc000695750 sp=0xc000695708 pc=0x988731
github.com/akiyosi/goqtframelesswindow._cgoexpwrap_0056b4a1b1b7_callbackQFramelessWindowb0996f_Event(0x2f86a10, 0x38698d0, 0x1)
	_cgo_gotypes.go:1631 +0x35 fp=0xc000695778 sp=0xc000695750 pc=0x983fb5
runtime.call32(0x0, 0x7ffe08de1a60, 0x7ffe08de1af0, 0x18)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/asm_amd64.s:519 +0x3b fp=0xc0006957a8 sp=0xc000695778 pc=0x5cc9cb
runtime.cgocallbackg1(0x0)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/cgocall.go:314 +0x177 fp=0xc000695820 sp=0xc0006957a8 pc=0x579ea7
runtime.cgocallbackg(0x0)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/cgocall.go:191 +0xc5 fp=0xc000695888 sp=0xc000695820 pc=0x579c95
runtime.cgocallback_gofunc(0x579b5f, 0xf38cd0, 0xc000695918, 0x2d49af0)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/asm_amd64.s:773 +0x9b fp=0xc0006958a8 sp=0xc000695888 pc=0x5cdf9b
runtime.asmcgocall(0xf38cd0, 0xc000695918)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/asm_amd64.s:620 +0x42 fp=0xc0006958b0 sp=0xc0006958a8 pc=0x5cde32
runtime.cgocall(0xf38cd0, 0xc000695918, 0x895e01)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/cgocall.go:131 +0x7f fp=0xc0006958e8 sp=0xc0006958b0 pc=0x579b5f
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
	_cgo_gotypes.go:2600 +0x49 fp=0xc000695918 sp=0xc0006958e8 pc=0x7d49b9
github.com/therecipe/qt/widgets.QApplication_Exec(...)
	/home/runner/work/goneovim/goneovim/src/github.com/therecipe/qt/widgets/widgets-minimal.go:2983
github.com/akiyosi/goneovim/editor.InitEditor(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/editor.go:341 +0xf5b fp=0xc000695ec0 sp=0xc000695918 pc=0xde847b
main.main()
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/cmd/goneovim/main.go:30 +0xa3 fp=0xc000695f98 sp=0xc000695ec0 pc=0xeac1d3
runtime.main()
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/proc.go:200 +0x20c fp=0xc000695fe0 sp=0xc000695f98 pc=0x5a3fdc
runtime.goexit()
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000695fe8 sp=0xc000695fe0 pc=0x5ce6e1

goroutine 34 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/proc.go:307
sync.runtime_notifyListWait(0xc0002c8150, 0xc00000002b)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/sema.go:510 +0xf9
sync.(*Cond).Wait(0xc0002c8140)
	/opt/hostedtoolcache/go/1.12.17/x64/src/sync/cond.go:56 +0x9e
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).dequeueNotifications(0xc0003056c0, 0x1, 0x1, 0x0)
	/home/runner/work/goneovim/goneovim/src/github.com/neovim/go-client/msgpack/rpc/rpc.go:659 +0x4c
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).runNotifications(0xc0003056c0)
	/home/runner/work/goneovim/goneovim/src/github.com/neovim/go-client/msgpack/rpc/rpc.go:671 +0x20c
created by github.com/neovim/go-client/msgpack/rpc.(*Endpoint).Serve
	/home/runner/work/goneovim/goneovim/src/github.com/neovim/go-client/msgpack/rpc/rpc.go:192 +0xdb

goroutine 8 [chan receive]:
github.com/akiyosi/goneovim/editor.InitEditor.func4(0xc000179400)
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/editor.go:313 +0x3b
created by github.com/akiyosi/goneovim/editor.InitEditor
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/editor.go:312 +0xe83

goroutine 18 [select]:
os/exec.(*Cmd).Start.func2(0xc0002fe000)
	/opt/hostedtoolcache/go/1.12.17/x64/src/os/exec/exec.go:416 +0xc4
created by os/exec.(*Cmd).Start
	/opt/hostedtoolcache/go/1.12.17/x64/src/os/exec/exec.go:415 +0x62d

goroutine 19 [IO wait]:
internal/poll.runtime_pollWait(0x7fe351a9ada8, 0x72, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0002d2138, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.12.17/x64/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.12.17/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0002d2120, 0xc00032b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.12.17/x64/src/internal/poll/fd_unix.go:169 +0x19b
os.(*File).read(...)
	/opt/hostedtoolcache/go/1.12.17/x64/src/os/file_unix.go:263
os.(*File).Read(0xc0002e6018, 0xc00032b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.12.17/x64/src/os/file.go:108 +0x70
bufio.(*Reader).fill(0xc0002d2240)
	/opt/hostedtoolcache/go/1.12.17/x64/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadByte(0xc0002d2240, 0xc0003056c0, 0xc0002c8180, 0xc00024e680)
	/opt/hostedtoolcache/go/1.12.17/x64/src/bufio/bufio.go:249 +0x39
github.com/neovim/go-client/msgpack.(*Decoder).Unpack(0xc0003140f0, 0x3, 0x0)
	/home/runner/work/goneovim/goneovim/src/github.com/neovim/go-client/msgpack/unpack.go:164 +0x55
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).Serve(0xc0003056c0, 0x0, 0x0)
	/home/runner/work/goneovim/goneovim/src/github.com/neovim/go-client/msgpack/rpc/rpc.go:195 +0xf0
github.com/neovim/go-client/nvim.(*Nvim).Serve(0xc000306570, 0x0, 0x0)
	/home/runner/work/goneovim/goneovim/src/github.com/neovim/go-client/nvim/nvim.go:53 +0x79
github.com/neovim/go-client/nvim.(*Nvim).startServe.func1(0xc000306570)
	/home/runner/work/goneovim/goneovim/src/github.com/neovim/go-client/nvim/nvim.go:59 +0x2b
created by github.com/neovim/go-client/nvim.(*Nvim).startServe
	/home/runner/work/goneovim/goneovim/src/github.com/neovim/go-client/nvim/nvim.go:58 +0x6c

goroutine 20 [semacquire]:
sync.runtime_SemacquireMutex(0xc00030659c, 0x0)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc000306598)
	/opt/hostedtoolcache/go/1.12.17/x64/src/sync/mutex.go:134 +0x109
github.com/neovim/go-client/nvim.(*Nvim).Serve(0xc000306570, 0x0, 0x0)
	/home/runner/work/goneovim/goneovim/src/github.com/neovim/go-client/nvim/nvim.go:51 +0x42
github.com/akiyosi/goneovim/editor.(*Workspace).startNvim.func3(0xc000257c00)
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/workspace.go:517 +0x36
created by github.com/akiyosi/goneovim/editor.(*Workspace).startNvim
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/workspace.go:516 +0x588

goroutine 31 [sleep]:
runtime.goparkunlock(...)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/proc.go:307
time.Sleep(0x1dcd6500)
	/opt/hostedtoolcache/go/1.12.17/x64/src/runtime/time.go:105 +0x159
github.com/akiyosi/goneovim/editor.(*Workspace).vimEnterProcess.func4(0xc000257c00)
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/workspace.go:349 +0x2a
created by github.com/akiyosi/goneovim/editor.(*Workspace).vimEnterProcess
	/home/runner/work/goneovim/goneovim/src/github.com/akiyosi/goneovim/editor/workspace.go:347 +0x111
```

Can it be something related to memory or something? I have my Pop_os installed in my SSD.

**Comment by akiyosi** [comment]
@lalitmee 
I'm sorry I haven't responded in a long time.
I am trying to fix the last report you reported.
Does the bug still occur with the latest binary?

https://github.com/akiyosi/goneovim/actions/runs/629716693

**Comment by lalitmee** [comment]
@akiyosi , 

Yeah, now I can use it. I am very happy after seeing this working.
Thank you so much for this awesome GUI Nvim and for helping me. :+1: 

I will see if I can contribute to it in the future in the process of learning Go. :innocent:

**Comment by akiyosi** [comment]
@lalitmee 
Thanks for confirming!

> Question: How can I check if goneovim is running right now in my neovim config file?

The following global variables can be used for detection :)

``` viml
if exists('g:goneovim')
   " do this here
endif 
```

**Comment by lalitmee** [comment]
@akiyosi , can I use this

```vim
let g:gonvim_fuzzy_ag_cmd = 'rg --hidden --ignore node_modules --follow --glob "!.git/*"'
```
instead of this

```vim
let g:gonvim_fuzzy_ag_cmd = 'pt --nogroup --column --nocolor'
```

I like `ripgrep`, that's why.

**Comment by akiyosi** [comment]
@lalitmee 
I think it's possible.
If there are any problems, please report them :)

**Comment by lalitmee** [comment]
@akiyosi , I just changed this command and when I tried `GonvimFuzzyAg`, it didn't work. It hanged. :thinking:

**Comment by akiyosi** [comment]
Hmmm, it could be that the `$PATH` is not passed, for example, and you should try specifying the full path to `rg`.

**Comment by lalitmee** [comment]
@akiyosi , I will try it out.

**Comment by akiyosi** [comment]
Closed.
If you have any problems, please reopen or post another issue.
