### ISSUE TITLE
[BUG] Cursor is missing

### ISSUE THREAD

**Issue by guolimin1995** [akiyosi/goneovim#309]
goneovim version: 0.5.1
neovim version: 0.6.1
os version: macos 10.15.4
when tt open coc-explore then tt close.
cursor is missing. not happened in iterm2

https://user-images.githubusercontent.com/29330637/149083605-1a8ee965-3c25-4e50-ac14-f1a27f8423b2.mov

**Comment by akiyosi** [comment]
Hi.
Thank you for this issue report.

I have fixed this problem. 
please try the following latest CI build.

https://github.com/akiyosi/goneovim/actions/runs/1698117338

**Comment by guolimin1995** [comment]
> Hi.
> Thank you for this issue report.
> 
> I have fixed this problem. 
> please try the following latest CI build.
> 
> https://github.com/akiyosi/goneovim/actions/runs/1698117338

tks. i'll try it.

**Comment by sigma2647** [comment]
Cursor missing It still happens when type :help `somthing`  it opens a split window after close the help menu

**Comment by akiyosi** [comment]
@guolimin1995 
Thanks for the response. I am waiting for your confirmation.

@sigma2647 
Thanks for the report.
Are you saying that you still have the cursor loss problem with the following latest CI?

> I have fixed this problem.
> please try the following latest CI build.
> 
> https://github.com/akiyosi/goneovim/actions/runs/1698117338


I have tried to reproduce the problem by displaying the help menu in `:help somthing`, but have not been able to reproduce the problem.

**Comment by guolimin1995** [comment]
> @guolimin1995 Thanks for the response. I am waiting for your confirmation.
> 
> @sigma2647 Thanks for the report. Are you saying that you still have the cursor loss problem with the following latest CI?
> 
> > I have fixed this problem.
> > please try the following latest CI build.
> > https://github.com/akiyosi/goneovim/actions/runs/1698117338
> 
> I have tried to reproduce the problem by displaying the help menu in `:help somthing`, but have not been able to reproduce the problem.

i use last CI of  https://github.com/akiyosi/goneovim/actions/runs/1698117338, it be fixed.

**Comment by guolimin1995** [comment]
> > @guolimin1995 Thanks for the response. I am waiting for your confirmation.
> > @sigma2647 Thanks for the report. Are you saying that you still have the cursor loss problem with the following latest CI?
> > > I have fixed this problem.
> > > please try the following latest CI build.
> > > https://github.com/akiyosi/goneovim/actions/runs/1698117338
> > 
> > 
> > I have tried to reproduce the problem by displaying the help menu in `:help somthing`, but have not been able to reproduce the problem.
> 
> i use last CI of https://github.com/akiyosi/goneovim/actions/runs/1698117338, it be fixed.

:help xxx it`s also fine.

**Comment by sigma2647** [comment]
> > > @guolimin1995 Thanks for the response. I am waiting for your confirmation.
> > > @sigma2647 Thanks for the report. Are you saying that you still have the cursor loss problem with the following latest CI?
> > > > I have fixed this problem.
> > > > please try the following latest CI build.
> > > > https://github.com/akiyosi/goneovim/actions/runs/1698117338
> > > 
> > > 
> > > I have tried to reproduce the problem by displaying the help menu in `:help somthing`, but have not been able to reproduce the problem.
> > 
> > 
> > i use last CI of https://github.com/akiyosi/goneovim/actions/runs/1698117338, it be fixed.
> 
> :help xxx it`s also fine.

Thanks ! that very Cool, I don't need to restart goneovim since after , how do I use this action ,should I using build version instead of release version?

**Comment by guolimin1995** [comment]
> > > > @guolimin1995 Thanks for the response. I am waiting for your confirmation.
> > > > @sigma2647 Thanks for the report. Are you saying that you still have the cursor loss problem with the following latest CI?
> > > > > I have fixed this problem.
> > > > > please try the following latest CI build.
> > > > > https://github.com/akiyosi/goneovim/actions/runs/1698117338
> > > > 
> > > > 
> > > > I have tried to reproduce the problem by displaying the help menu in `:help somthing`, but have not been able to reproduce the problem.
> > > 
> > > 
> > > i use last CI of https://github.com/akiyosi/goneovim/actions/runs/1698117338, it be fixed.
> > 
> > :help xxx it`s also fine.
> 
> Thanks ! that very Cool, I don't need to restart goneovim since after , how do I use this action ,should I using build version instead of release version?

download CI in this action. don't need to build.

**Comment by sigma2647** [comment]
> > > > > @guolimin1995 Thanks for the response. I am waiting for your confirmation.
> > > > > @sigma2647 Thanks for the report. Are you saying that you still have the cursor loss problem with the following latest CI?
> > > > > > I have fixed this problem.
> > > > > > please try the following latest CI build.
> > > > > > https://github.com/akiyosi/goneovim/actions/runs/1698117338
> > > > > 
> > > > > 
> > > > > I have tried to reproduce the problem by displaying the help menu in `:help somthing`, but have not been able to reproduce the problem.
> > > > 
> > > > 
> > > > i use last CI of https://github.com/akiyosi/goneovim/actions/runs/1698117338, it be fixed.
> > > 
> > > 
> > > :help xxx it`s also fine.
> > 
> > 
> > Thanks ! that very Cool, I don't need to restart goneovim since after , how do I use this action ,should I using build version instead of release version?
> 
> download CI in this action. don't need to build.

Got it, thank you sooooo much
