### ISSUE TITLE
External file browser doesn't work as expected

### ISSUE THREAD

**Issue by smolck** [akiyosi/goneovim#71]
Currently, when I execute `:GonvimFilerOpen`, nothing is shown in the file explorer, my statusline disappears, and I can't type in the currently open file until I press `<Esc>`:

![image](https://user-images.githubusercontent.com/46855713/68079150-cdc8b680-fdb2-11e9-8ae3-860f2968e8a0.png)

**Comment by akiyosi** [comment]
Probably in conflict with other plugins (maybe lightline?).
I implemented the external filer with vimscript, but it seems to be bad. 

Is it possible to check if the filer is displayed with `goneovim -u NONE` ?

**Comment by smolck** [comment]
> Is it possible to check if the filer is displayed with goneovim -u NONE ?

Yes; but same problems still occur, so I don't think it's a plugin conflict. I have noticed that the currently open file's text does show, so I was wrong there, but other than that the problems are still as I said above.

Also, I have noticed that GoNeovim crashes if I press `l` (lowercase L) with the filer open.

> I implemented the external filer with vimscript, but it seems to be bad.

Maybe switching over to Lua could help; if nothing else it will probably be quite a bit faster than Vimscript.

**Comment by akiyosi** [comment]
thx.
This problem cannot be reproduced in my environment.
Tell me more about your environment.

* your OS
* nvim version
* the content of `~/.goneovim/setting.toml`
* minimal init.vim to reproduce the probrem

> Maybe switching over to Lua could help; if nothing else it will probably be quite a bit faster than Vimscript.

I see. 
I wanted to make it work with remote attachments, so I implemented it with vim script.
Certainly, the implementation with lua can be expected to be even faster.

**Comment by smolck** [comment]
> * your OS

Arch Linux

> * nvim version

NVIM v0.5.0-137-g93626b8af ([latest neovim-nightly from AUR](https://aur.archlinux.org/packages/neovim-nightly/))

> * the content of `~/.goneovim/setting.toml`

```
[Editor]
# ExtMessages = true
ExtPopupmenu = true
ExtTabline = false
ExtCmdline = true
FontFamily = "Iosevka Extrabold"
FontSize = 12

[Workspace]
PathStyle = "minimum"

# [Statusline]
# Visible = true
```

> * minimal init.vim to reproduce the probrem

It happens if I have no `init.vim` at all, so with it temporarily renamed to `in.vim` (so it isn't loaded by Neovim) the problems still occur.

**Comment by smolck** [comment]
> I see.
> I wanted to make it work with remote attachments, so I implemented it with vim script.
> Certainly, the implementation with lua can be expected to be even faster.

I'm not really sure if that's a necessary change though, now that I think about it. It seems it could be something else, since the filer opens. The main problem is that it doesn't show anything inside of it, and I'm not sure if that's Vimscript's fault.

Is there a way to run GoNeovim with an older version of Neovim? E.g. `goneovim --nvim /path/to/nvim` or something? I wonder if the problems are due to my using the latest Neovim nightly.

**Comment by akiyosi** [comment]
I got your environmental information, so this weekend I will prepare a VM with the same environment and check it out

> Is there a way to run GoNeovim with an older version of Neovim? E.g. goneovim --nvim /path/to/nvim or something? I wonder if the problems are due to my using the latest Neovim nightly.

Currently, goneovim cannot specify a backend nvim.
The `--nvim` option is a good idea. I will add that option by the next release.

**Comment by smolck** [comment]
With the https://github.com/akiyosi/goneovim/tree/filer-lua branch, the filer works, but it appears cut off, and also my statusbar does not show:

![image](https://user-images.githubusercontent.com/46855713/68995647-aadbdf00-0855-11ea-89fe-f3e98b128317.png)

**Comment by Famiu** [comment]
I'm also facing this issue, a fix would be appreciated

**Comment by akiyosi** [comment]
@Famiu 
Hi
Sorry, it actually doesn't work well with nvim v0.5.0 at the moment.
I will fix it in the next release.

**Comment by pierreglaser** [comment]
Hi, for the record, I'm also experiencing this.
